/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pw.proz;





import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.GridPane;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;
import javafx.stage.Stage;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;

public class App extends Application {
    /*


    Rozdział modelu od widoku
    Elementy modelu - potwory, postacie i wkipunek
    elementy widoku - porzekazane do kontrolera

    Obiektowość
    jedna klasa na postać
    klasa na umiejetnosci
    BEZ WIDOKÓW
    ZMIENIC random thread na random po prsotu
    Klasa zarzadzajaca calym modelem




     */
    @Override
    public void start(Stage primaryStage) throws IOException {




        FXMLLoader loader = new FXMLLoader(getClass().getResource("/Window.fxml"));
        Parent root = loader.load();

        Controller myController = loader.getController();

        primaryStage.setTitle("Dungeon Explorer");
        primaryStage.setScene(new Scene(root, 1400, 1040));
        primaryStage.setResizable(false);
        primaryStage.show();

        ModelOrganizer model = new ModelOrganizer();
        for(int i=0; i<5; i++){
          model.addCharacter(0, 12, i+6, 1, "goblin");
        }
        model.addCharacter(1, 18,10,3, "Demon Warrior");
        model.addCharacter(2, 18,15,10, "Beholder");
        model.addCharacter(3, 4,14,3, "Sir Iam Mckellen");
        model.addCharacter(4, 4,10,3, "Papito the Foul");



      myController.initialized(model);


    }


    public static void main(String[] args) {
        launch(args);
    }
}
